server:
  port: 3000
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: 123456
    
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true